# Generated by Django 5.1.1 on 2026-03-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_name_en_category_name_ko_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
