# Generated by Django 5.1.1 on 2025-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='description_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_ko',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='description_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='title_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='title_ko',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='title_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='title_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
