# Generated by Django 5.1.1 on 2026-03-02 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_advice_description_en_advice_description_ko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['-created_date'], 'verbose_name': 'Foydalanuvchi manzili', 'verbose_name_plural': 'Foydalanuvchi manzillari'},
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='apartment',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Xonadon'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='floor',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Qavat'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
